# Sample configuration to train the lite model on
# (grapheme, phoneme) pair predictions


# REPLICABILITY
SEED: 2023


# FILEPATHS
train_filepath: data/train_mapped.pkl
val_filepath: data/val_mapped.pkl
gp2idx_filepath: data/gp2idx.txt
chr2idx_filepath: data/chr2idx.txt


# TORCH MODEL
torch_model:
  enc_emb_dim: 64
  dec_emb_dim: 128
  encgru:
    hidden_size: 512
    batch_first: true
  enc_take_last: false
  decgru:
    hidden_size: 512
  cls_lin_dim: 2048
  max_steps: 35


# DATA LOADERS
train_loader:
  batch_size: 512
  shuffle: true
  num_workers: 4
val_loader:
  batch_size: 1024
  shuffle: false
  num_workers: 4


# TRAINER 
trainer:
  max_saved_ckpts: 3
  init_tf_rate: 0.85
  optimizer:
  # using AdamW
    lr: 5.0e-4
    weight_decay: 0.01
    amsgrad: true
  criterion:
  # using cross entropy without reduction
    reduction: 'none'
    label_smoothing: 0.0
  scaler:
    use: true
  lr_scheduler:
    use: true
    # using ReduceOnPlateau
    configs:
      mode: min
      factor: 0.5
      patience: 5
      min_lr: 1.0e-7
  tf_scheduler:
    use: true
    min_init_epochs: 20
    min_tf_rate: 0.5
    interval: 0.1
  dropout_scheduler:
    use: false


# EXPERIMENTS
exp:
  folder: exp/some-name
  finetune:
    use: false
    ckpt: 
  annotation:
  epoch: 50
  wandb:
    use: false
    configs:
      reinit: true
      project: gppred
      entity: Astromsoc
  

# INFERENCE MODEL ARCHITECTURE
lite_model:
  input_dim: 64
  hidden_dim: 128
  # either make init-h trainable or always 0
  #   choices: ["zero-trainable", "zero-frozen", "random"]
  inith_opt: "zero-frozen"
